language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --no-interaction --no-progress

script:
  - phpunit

notifications:
  email: false
