ARG PHP_VERSION=7.3

FROM php:${PHP_VERSION}-cli

COPY --from=composer:2.2.7 /usr/bin/composer /usr/local/bin/composer

RUN apt-get update && apt-get install --no-install-recommends -y git unzip wget gnupg dirmngr \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo 'date.timezone = UTC' > /usr/local/etc/php/conf.d/timezone.ini
RUN echo 'memory_limit = 1G' > /usr/local/etc/php/conf.d/memory_limit.ini

RUN mkdir ~/.gnupg
RUN echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf

RUN if [ "$PHP_VERSION" != "7.1.33" ]; then \
    wget -O phive.phar "https://github.com/phar-io/phive/releases/download/0.15.0/phive-0.15.0.phar" && \
    wget -O phive.phar.asc "https://github.com/phar-io/phive/releases/download/0.15.0/phive-0.15.0.phar.asc" && \
    gpg --no-tty --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79 && \
    gpg --no-tty --verify phive.phar.asc phive.phar && \
    rm phive.phar.asc && \
    chmod +x phive.phar && \
    mv phive.phar /usr/local/bin/phive ; fi

WORKDIR /app
